name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker build . --file Dockerfile --tag gtcs2110/cs2110docker:$IMAGE_TAG
